version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fault_db_server
    restart: always
    environment:
      POSTGRES_USER: ${APP_CONFIG__DB__USER:-postgres}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD:-postgres}
      POSTGRES_DB: ${APP_CONFIG__DB__NAME:-fault_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: